---
api:
  port: 'SERVICE_PORT'
  apiKeyHash: 'API_KEY_HASH'
database:
  host: 'POSTGRES_HOST'
  port: 'POSTGRES_PORT'
  user: 'POSTGRES_USER'
  password: 'POSTGRES_PASSWORD'
  name: 'POSTGRES_DB'
ergo:
  mnemonic: 'MNEMONIC'
bitcoin:
  rpc:
    username: 'BITCOIN_RPC_USERNAME'
    password: 'BITCOIN_RPC_PASSWORD'
bitcoinRunes:
  unisat:
    apiKey: 'UNISAT_API_KEY'
cardano:
  koios:
    authToken: 'KOIOS_AUTH_TOKEN'
  blockfrost:
    projectId: 'BLOCKFROST_PROJECT_ID'
ethereum:
  rpc:
    authToken: 'ETHEREUM_RPC_AUTH_TOKEN'
binance:
  rpc:
    authToken: 'BINANCE_RPC_AUTH_TOKEN'
overrideLokiBasicAuth: 'OVERRIDE_LOKI_BASIC_AUTH'
