---
network: ergo
ergo:
  networkType: Mainnet
  secret: 30ec2689d8920095a34193de5b313dc84b178fd827d568be96f85bba12b69db0
  node:
    url: 'http://sample-node.com'
  mnemonic: ''
  fee: '1100000'
  minBoxValue: '1100000'
path:
  addresses: tests/config
  tokens: tests/config/tokens.test.json
logs:
  - type: 'console'
    level: 'error'
observation:
  confirmation: 10
